"""add fecha_cumplida to manifiestos_avansat

Revision ID: 70008444456b
Revises: e2b4a6c8d0f1
Create Date: 2026-09-16 15:28:40.269687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70008444456b'
down_revision: Union[str, Sequence[str], None] = 'e2b4a6c8d0f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manifiestos_avansat', sa.Column('fecha_cumplida', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('manifiestos_avansat', 'fecha_cumplida')
    # ### end Alembic commands ###
